# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm
      - security
    commit-message:
      prefix: "⬆️ build"
      include: scope
    schedule:
      interval: "weekly"
      day: "sunday"
      timezone: Europe/Paris
      time: "16:00"
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    open-pull-requests-limit: 5
    directory: "/"
    ignore:
      -
        dependency-name: "node"
        update-types:
          - "version-update:semver-major"
    labels:
      - dependencies
      - docker
      - security
    commit-message:
      prefix: "⬆️ build"
      include: scope
    schedule:
      interval: "weekly"
      day: "sunday"
      timezone: Europe/Paris
      time: "16:00"
    groups:
      all-docker-images:
        patterns:
          - "*"

  - package-ecosystem: "docker-compose"
    open-pull-requests-limit: 5
    directory: "/"
    labels:
      - dependencies
      - docker-compose
      - security
    commit-message:
      prefix: "⬆️ build"
      include: scope
    schedule:
      interval: "weekly"
      day: "sunday"
      timezone: Europe/Paris
      time: "16:00"
    groups:
      all-docker-compose-images:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 5
    directory: "/"
    labels:
      - dependencies
      - github_actions
      - security
    commit-message:
      prefix: "⬆️ build"
      include: scope
    schedule:
      interval: "weekly"
      day: "sunday"
      timezone: Europe/Paris
      time: "16:00"
    groups:
      all-actions:
        patterns: [ "*" ]
